name: Waka Readme

on:
  schedule:
    # 每天 UTC 0:00 自动更新
    - cron: '0 0 * * *'
  workflow_dispatch: # 支持手动触发运行

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_TIME: true
